title:  "Abenteuer Irland"
description: "Mary O'Keeffe nimmt Sie auf eine Reise in das grüne Paradies."
exclude: [img-src, Gemfile, Gemfile.lock, Rakefile, Rakefile.config, abenteuer-irland.sublime-project, abenteuer-irland.sublime-workspace]
url: http://arlol.github.io
baseurl: /abenteuer-irland/
language: de
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all
sass:
  style: compressed
