title:  "Abenteuer Irland"
description: "Mary O'Keeffe nimmt Sie auf eine Reise in das grüne Paradies."
exclude: [img-src, Gemfile, Gemfile.lock, Rakefile, Rakefile.config, abenteuer-irland.sublime-project, abenteuer-irland.sublime-workspace]
url: https://arlol.github.io
baseurl: /abenteuer-irland/
language: de
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all
sass:
  style: compressed
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
