title:  "Abenteuer Irland"
description: "Das ist die deutsche Seite."
exclude: [img-src, Gemfile, Gemfile.lock, Rakefile, abenteuer-irland.sublime-project, abenteuer-irland.sublime-workspace]
markdown: kramdown
analytics_id: UA-25657814-1
languages:
 - short: en
   name: English
   flag: english.png
   flag_width: 30
   flag_height: 15
 - short: de
   name: Deutsch
   flag: german.png
   flag_width: 30
   flag_height: 18
